### ISSUE TITLE
Multiple level 1 headings are used on this page

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/keystone#13]
Page: [What’s new in NetApp Service Engine](https://docs.netapp.com/us-en/keystone/rn_whats_new.html)

The following titles are formatted as level 1 headings:

Features introduced in NetApp Keystone Flex Subscription 2.0.1
Features introduced in NetApp Keystone Flex Subscription 2.0

They should be level 2 headings.

**Comment by netapp-manini** [comment]
@netapp-bcammett this was resolved in the last release: https://docs.netapp.com/us-en/keystone/rn_whats_new.html

**Comment by netapp-bcammett** [comment]
Hi Manini,

Looks good. Thank you for confirming. 

I did notice another issue when looking at the what's new page:

For more information on this feature, see the following links:
* Operational model, roles, and responsibilities
* Tenancy and multi-tenancy in Flex Subscription
* View Flex Subscription Dashboard
* View reports
* Managing subscriptions
* Managing tenants and subtenants
* Define networks for tenants and subtenants

This is a syntax error. The bullets aren't showing up because there isn't an empty line in between the sentence and the list.

**Comment by netapp-manini** [comment]
This was fixed in the last release.
