### ISSUE TITLE
Lead is missing and the format of the Steps is incorrect

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/keystone#15]
Page: [Raise a service request](https://docs.netapp.com/us-en/keystone/sewebiug_raise_a_service_request.html)

This page doesn't have a lead and "Steps" shouldn't be a level 3 heading. It should be formatted as follows:

.Steps

You can find more details in the Contributor's Guide:
https://docs.netapp.com/us-en/contribute/asciidoc_syntax.html#steps

**Comment by netapp-manini** [comment]
This was a part of the original file before conversion, and fixed now.

https://docs.netapp.com/us-en/keystone/sewebiug_raise_a_service_request.html

**Comment by netapp-manini** [comment]
All instances have been fixed in the last release. @netapp-manishc can you please close this issue?
