### ISSUE TITLE
Steps should not be a heading

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/keystone#16]
Page: [Modify user details](https://docs.netapp.com/us-en/keystone/sewebiug_modify_user_details.html)

Please run a search across all files to identify where "=== Steps" exists and change to ".Steps"

**Comment by netapp-manini** [comment]
This is fixed: https://docs.netapp.com/us-en/keystone/sewebiug_modify_user_details.html

**Comment by netapp-manini** [comment]
All instances have been fixed in the last release. @netapp-manishc can you please close this issue?
