### ISSUE TITLE
Table in this topic should be text, not graphic

### ISSUE THREAD

**Issue by adamn-ntap** [NetAppDocs/keystone#21]
Page: [Performance Service Levels](https://docs.netapp.com/us-en/keystone/nkfsosm_performance.html)

The table is a screenshot and should instead be an actual table. Among other things, when a user goes from English to another language, the text within the graphic remains in English. Furthermore, none of the text in the graphic is searchable.

**Comment by netapp-manini** [comment]
Hi @adamn-ntap, I am working on this, and it will be released in early December.

**Comment by netapp-manini** [comment]
This has been released today at 
https://docs.netapp.com/us-en/keystone/nkfsosm_performance.html
