### ISSUE TITLE
Wrong/internal URL in these instructions

### ISSUE THREAD

**Issue by innergy** [NetAppDocs/keystone#25]
Page: [Working with Cloud Manager](https://docs.netapp.com/us-en/keystone/sewebiug_working_with_cloud_manager.html)

View the status of the connection to Cloud Manager

https://jira.ngage.netapp.com/browse/NSEKEY-1703

**Comment by netapp-manini** [comment]
Thanks for writing in, @innergy 
We are looking into this issue.

**Comment by netapp-manini** [comment]
The topic has been removed. Closing this issue as resolved.

[Working with Cloud Manager](https://docs.netapp.com/us-en/keystone/sewebiug_working_with_cloud_manager.html)
