### ISSUE TITLE
fix adoc list notation

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/keystone#28]
Page: [Documentation for NetApp Keystone Flex Subscription](https://docs.netapp.com/us-en/keystone/index.html)

Reference area:
![image](https://user-images.githubusercontent.com/56453501/165792691-7e29c60f-7ad7-4960-8075-24e6b0a46389.png)

I suspect that there needs to be a blank line before the list. There should be actual bullets there, not asterisks. This is also causing errors in the localized pages, so be sure to check them after updating English, and open a discussion if they don't pick up the formatting correction after the English update.

**Comment by netapp-manini** [comment]
Fixed at https://docs.netapp.com/us-en/keystone/
