### ISSUE TITLE
Broken link in sidebar

### ISSUE THREAD

**Issue by netapp-bcammett** [NetAppDocs/keystone#37]
Page: [Keystone service terms and descriptions](https://docs.netapp.com/us-en/keystone/nkfsosm_service_terms_and_description_overview.html)

The "Service capacity definitions" link doesn't work in the sidebar. It's pointing to this URL:
https://docs.netapp.com/us-en/keystone/nkfsosm_keystone_service_capacity_definitions.html

**Comment by netapp-manini** [comment]
Thanks @netapp-bcammett for bringing this to my notice. This will be fixed soon.

**Comment by netapp-manini** [comment]
This issue is fixed.
