### ISSUE TITLE
image repetition

### ISSUE THREAD

**Issue by ntap-bmegan** [NetAppDocs/keystone#41]
### Page URL

https://docs.netapp.com/us-en/keystone/aiq-keystone-details.html

### Page title

Digital Advisor dashboard and reporting for Keystone

### Summary

The same image is shown three times in immediate succession. 

![image](https://github.com/NetAppDocs/keystone/assets/56453501/5024e7f0-cfca-456d-964b-7732d6bf5beb)

### Public issues must not contain sensitive information

- [X] This issue contains no sensitive information.

**Comment by netapp-manini** [comment]
Thanks for identifying this issue, @ntap-bmegan. I will discuss this with you. I see some anomaly.

**Comment by netapp-manini** [comment]
Fixed.
