### ISSUE TITLE
Typo in Snapshot naming

### ISSUE THREAD

**Issue by hashbangbinbash** [NetAppDocs/keystone#6]
Page: [Create a new file share](https://docs.netapp.com/us-en/keystone/sewebiug_create_a_new_file_share.html)

Hourly. Specify which minute (of the hour) to take snapshot and the number of hourly snapshots to retain.

**Daily**. Specify when (hour and minute) to take the snapshot the number of **hourly** snapshots to retain.

**Comment by netapp-manini** [comment]
Fixed at https://docs.netapp.com/us-en/keystone/sewebiug_create_a_new_file_share.html#steps

**Comment by netapp-manini** [comment]
@hashbangbinbash please close this issue if you think the resolution is offered.
