### ISSUE TITLE
Request to Clarify Operating Model

### ISSUE THREAD

**Issue by hashbangbinbash** [NetAppDocs/keystone#9]
Page: [Service Offer Details](https://docs.netapp.com/us-en/keystone/nkfsfaq_service_offer_details.html)

Hi, is it possible to clarify or build out this statement a bit more? This only refers to the NetApp Operated Model through NSE. Can you add customer operated answer into this also? thanks

**How does the customer access the storage?**
The customer can only provision storage and change provisioned storage to available settings, either through a management portal or through APIs. The customer cannot directly log in to the storage equipment. For example, the customer is not provided with NetApp ONTAP System Manager or administrative access to the systems.

**Comment by netapp-manini** [comment]
Added at: https://docs.netapp.com/us-en/keystone/nkfsfaq_operations_and_support.html

**Comment by hashbangbinbash** [comment]
thanks
